# -*- coding: utf-8 -*-
"""CFL_Base_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_NNVoLKccJn6hqmxCrxwGojDnDWrgCSP
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from typing import Dict, Tuple, Optional, List

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import roc_auc_score, roc_curve, auc
import matplotlib.pyplot as plt
from scipy.optimize import minimize, minimize_scalar
np.set_printoptions(suppress=True, linewidth=120)

def load_dataset(path: str, target: Optional[str] = None, id_col: Optional[str] = None) -> Tuple[np.ndarray, np.ndarray, List[str]]:
    """
    CSV 파일에서 데이터셋을 로드하고 전처리하는 함수
    """
    df = pd.read_csv(path)
    if id_col is not None and id_col in df.columns:
        df = df.drop(columns=[id_col])

    if target is None:
        for cand in ["target", "label", "y", "class", "Bankrupt?"]:
            if cand in df.columns:
                target = cand
                break
        if target is None:
            target = df.columns[-1]
    y = df[target].values
    X_df = df.drop(columns=[target])

    nunique = X_df.nunique(dropna=False)
    const_cols = nunique[nunique <= 1].index.tolist()
    if const_cols:
        print(f"상수 변수 제거: {const_cols}")
        X_df = X_df.drop(columns=const_cols)

    for col in X_df.columns:
        if not np.issubdtype(X_df[col].dtype, np.number):
            X_df[col] = pd.factorize(X_df[col], sort=True)[0]

    if y.dtype.kind not in ("i", "u", "f"):
        y_enc, _ = pd.factorize(y, sort=True)
        y = y_enc
    else:
        uniques = np.unique(y)
        mapper = {val: i for i, val in enumerate(sorted(uniques))}
        y = np.vectorize(mapper.get)(y)

    if len(np.unique(y)) != 2:
        raise ValueError("This script expects a binary target.")

    return X_df.values.astype(float), y.astype(int), X_df.columns.tolist()

# --------------------------------------------------------------------------------------
# NI computation & Confusion counting
# --------------------------------------------------------------------------------------

def ni_from_confusion(conf: np.ndarray, m: int = 2) -> float:
    """
    혼동 행렬로부터 Normalized Mutual Information (NI) 점수를 계산
    
    Computes NI = I(C;K) / H(C) where:
    - C is the true class (rows of confusion matrix)
    - K is the predicted class or reject state (columns of confusion matrix)
    
    Parameters:
        conf: Confusion matrix of shape (m, m) or (m, m+1)
              - (m, m): Standard confusion matrix without reject option
              - (m, m+1): With reject option, where column m is the reject state
        m: Number of classes (default 2 for binary classification)
    
    Returns:
        Normalized Information score in [0, 1]
        
    Note: When reject option is present (cols = m+1), the reject column is included
          in the mutual information calculation, ensuring p(K=j) sums to 1 over all
          predicted states (including reject), consistent with arXiv:1307.5730.
    """
    conf = conf.astype(float)
    if conf.ndim != 2: raise ValueError("conf must be 2D")
    rows, cols = conf.shape
    if rows != m: raise ValueError("conf rows must equal number of classes m")
    if cols not in (m, m + 1): raise ValueError("conf cols must be m or m+1")
    n = conf.sum()
    if n <= 0: return 0.0
    
    eps = 1e-10  # Small constant for numerical stability to avoid log(0)
    Ci = conf.sum(axis=1)  # Row sums: p(C=i) denominator
    
    # Include reject column in col_sums if present (cols == m+1)
    # This ensures p(K=j) is computed over all predicted states and sums to 1
    col_sums = conf.sum(axis=0)  # Sum over all columns (m or m+1)
    
    if np.any(Ci == 0): return 0.0

    # Compute MI numerator: sum over all columns including reject if present
    # I(C;K) = sum_i sum_j n_ij * log2(p(C=i,K=j) / (p(C=i) * p(K=j)))
    num = 0.0
    for i in range(m):
        for j in range(cols):  # Loop over all columns (m or m+1 if reject present)
            cij = conf[i, j]
            if cij <= eps: continue
            if col_sums[j] <= eps: continue
            
            pij_given_i = cij / Ci[i]  # p(K=j | C=i)
            pj = col_sums[j] / n       # p(K=j) - now includes reject if present
            num += cij * math.log2(pij_given_i / pj)

    # Compute denominator: -n * H(C) = -sum_i Ci * log2(Ci/n)
    # Entropy over true classes (rows)
    den = 0.0
    for i in range(m):
        if Ci[i] <= eps: continue
        pi = Ci[i] / n
        den += Ci[i] * math.log2(pi)

    if abs(den) < eps: return 0.0
    NI = -num / den
    return float(max(0.0, min(1.0, NI)))

@dataclass
class BinaryCounts:
    """
    이진 분류 결과(TN, FP, FN, TP, 기권)를 저장하는 데이터 클래스
    """
    TN: int; FP: int; FN: int; TP: int; RN: int; RP: int
    def to_matrix_no_reject(self) -> np.ndarray: return np.array([[self.TN, self.FP], [self.FN, self.TP]], dtype=int)
    def to_matrix_with_reject(self) -> np.ndarray: return np.array([[self.TN, self.FP, self.RN], [self.FN, self.TP, self.RP]], dtype=int)
    def merge(self, other: 'BinaryCounts') -> 'BinaryCounts':
        return BinaryCounts(self.TN + other.TN, self.FP + other.FP, self.FN + other.FN, self.TP + other.TP, self.RN + other.RN, self.RP + other.RP)

def count_binary(y_true: np.ndarray, y_pred: np.ndarray) -> BinaryCounts:
    """
    실제값과 예측값으로부터 이진 분류 결과(혼동 행렬 요소)를 카운트
    """
    TN = FP = FN = TP = RN = RP = 0
    for t, p in zip(y_true, y_pred):
        if p == -1:
            if t == 0: RN += 1
            else: RP += 1
        else:
            if t == 0 and p == 0: TN += 1
            elif t == 0 and p == 1: FP += 1
            elif t == 1 and p == 0: FN += 1
            elif t == 1 and p == 1: TP += 1
    return BinaryCounts(TN, FP, FN, TP, RN, RP)

def prf2_from_counts(cnt: BinaryCounts) -> Tuple[float, float, float]:
    """
    BinaryCounts 객체로부터 Precision, Recall, F2-score를 계산
    """
    TP, FP, FN = cnt.TP, cnt.FP, cnt.FN
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    beta = 2.0
    if precision + recall == 0: f2 = 0.0
    else: f2 = (1 + beta ** 2) * (precision * recall) / (beta ** 2 * precision + recall)
    return precision, recall, f2

# --------------------------------------------------------------------------------------
# Decision rules & optimization targets
# --------------------------------------------------------------------------------------

def pred_nonabstain_with_alpha(p_pos: np.ndarray, alpha_N: float) -> np.ndarray:
    theta = alpha_N / (1.0 + alpha_N)
    return (p_pos >= theta).astype(int)

def pred_abstain_with_Tr(p_pos: np.ndarray, TrN: float, TrP: float) -> np.ndarray:
    p_neg = 1.0 - p_pos
    denomN = max(1e-12, 1.0 - TrN); denomP = max(1e-12, 1.0 - TrP)
    sN = p_neg / denomN; sP = p_pos / denomP
    y_pred = np.full_like(p_pos, fill_value=-1, dtype=int)
    choose_mask = (np.maximum(sN, sP) >= 1.0)
    choose_idx = np.where(choose_mask)[0]
    y_pred[choose_idx] = (sP[choose_idx] >= sN[choose_idx]).astype(int)
    return y_pred

def objective_alpha(alpha: float, p_pos: np.ndarray, y_true: np.ndarray) -> float:
    y_pred = pred_nonabstain_with_alpha(p_pos, alpha)
    return -ni_from_confusion(count_binary(y_true, y_pred).to_matrix_no_reject(), m=2)

def _uv_to_Tr(u: float, v: float, eps: float = 1e-6) -> Tuple[float, float]:
    a = 1.0 / (1.0 + math.exp(-u)); b = 1.0 / (1.0 + math.exp(-v))
    TrN = (1.0 - eps) * a; TrP = (1.0 - eps) * b * (1.0 - a)
    return TrN, TrP

def _Tr_to_uv(TrN: float, TrP: float, eps: float = 1e-6) -> Tuple[float, float]:
    a = TrN / (1.0 - eps)
    a = max(eps, min(1.0 - eps, a))
    u = math.log(a / (1.0 - a))
    if (1.0 - a) > eps:
        b = TrP / ((1.0 - eps) * (1.0 - a))
        b = max(eps, min(1.0 - eps, b))
    else:
        b = 0.5
    v = math.log(b / (1.0 - b))
    return u, v

def objective_uv_Tr(params: np.ndarray, p_pos: np.ndarray, y_true: np.ndarray, alpha_mean: float) -> float:
    u, v = float(params[0]), float(params[1])
    TrN, TrP = _uv_to_Tr(u, v)
    denom = 1.0 - TrN - TrP
    if denom <= 1e-9:
        return 1e6
    lam_FP = alpha_mean
    lam_RN = (TrN * (1.0 - TrP) - TrN * TrP * lam_FP) / denom
    lam_RP = (-TrN * TrP + (1.0 - TrN) * lam_FP * TrP) / denom
    if lam_RP > 1.0 or lam_RN > lam_FP or lam_RP < 0 or lam_RN < 0:
        return 1e6
    y_pred = pred_abstain_with_Tr(p_pos, TrN, TrP)
    ni = ni_from_confusion(count_binary(y_true, y_pred).to_matrix_with_reject(), m=2)
    return -ni

# --------------------------------------------------------------------------------------
# Training helpers
# --------------------------------------------------------------------------------------

@dataclass
class ModelResult:
    """
    모델의 최종 성능 지표 및 표준편차를 저장하는 데이터 클래스
    """
    name: str; counts: BinaryCounts;
    precision: float; recall: float; f2: float; ni: float;
    reject_rate_overall: float;
    precision_std: float; recall_std: float; f2_std: float; ni_std: float;
    reject_rate_overall_std: float;
    reject_rate_by_class: Tuple[float, float]; eq_cost_matrix: np.ndarray

class Aggregator:
    """
    여러 반복 실험 결과를 누적하고 요약하는 클래스
    """
    def __init__(self, model_names: List[str]):
        self._all_counts: Dict[str, List[BinaryCounts]] = {k: [] for k in model_names}
        self._eq_cost_accum: Dict[str, List[np.ndarray]] = {k: [] for k in model_names}

    def add(self, model_name: str, cnt: BinaryCounts, eq_cost: np.ndarray):
        self._all_counts[model_name].append(cnt)
        self._eq_cost_accum[model_name].append(eq_cost)

    def summarize(self) -> Dict[str, ModelResult]:
        out = {}
        for name, counts_list in self._all_counts.items():
            # 1. 각 반복(run)에 대한 개별 성능 지표 계산
            run_metrics = {
                'precision': [], 'recall': [], 'f2': [], 'ni': [], 'reject_rate': []
            }
            for cnt in counts_list:
                prec, rec, f2 = prf2_from_counts(cnt)
                run_metrics['precision'].append(prec)
                run_metrics['recall'].append(rec)
                run_metrics['f2'].append(f2)

                total = cnt.TN + cnt.FP + cnt.FN + cnt.TP + cnt.RN + cnt.RP
                if cnt.RN + cnt.RP > 0:
                    conf = cnt.to_matrix_with_reject()
                    rej_rate = (cnt.RN + cnt.RP) / total if total > 0 else 0.0
                    ni = ni_from_confusion(conf, m=2)
                else:
                    rej_rate = 0.0
                    ni = ni_from_confusion(cnt.to_matrix_no_reject(), m=2)
                run_metrics['reject_rate'].append(rej_rate)
                run_metrics['ni'].append(ni)

            # 2. 각 지표의 표준편차 계산
            prec_std = np.std(run_metrics['precision'])
            rec_std = np.std(run_metrics['recall'])
            f2_std = np.std(run_metrics['f2'])
            ni_std = np.std(run_metrics['ni'])
            rej_std = np.std(run_metrics['reject_rate'])

            # 3. 전체 반복에 대한 통합 성능 지표 계산 (기존 방식)
            total_counts = BinaryCounts(0,0,0,0,0,0)
            for cnt in counts_list:
                total_counts = total_counts.merge(cnt)

            agg_prec, agg_rec, agg_f2 = prf2_from_counts(total_counts)
            if total_counts.RN + total_counts.RP > 0:
                conf = total_counts.to_matrix_with_reject(); total = conf.sum()
                agg_rej_overall = (total_counts.RN + total_counts.RP) / total
                CN = conf[0, :].sum(); CP = conf[1, :].sum()
                rejN = conf[0, 2] / CN if CN > 0 else 0.0
                rejP = conf[1, 2] / CP if CP > 0 else 0.0
                agg_ni = ni_from_confusion(conf, m=2)
            else:
                agg_rej_overall, rejN, rejP = 0.0, 0.0, 0.0
                agg_ni = ni_from_confusion(total_counts.to_matrix_no_reject(), m=2)

            mats = self._eq_cost_accum[name]
            if mats:
                max_cols = max(mat.shape[1] for mat in mats)
                mats_norm = [np.hstack([mat, np.zeros((2, max_cols - mat.shape[1]))]) if mat.shape[1] < max_cols else mat for mat in mats]
                eq_avg = np.mean(np.stack(mats_norm, axis=0), axis=0)
            else: eq_avg = np.zeros((2, 2))

            # 4. 최종 결과 객체 생성
            out[name] = ModelResult(
                name=name, counts=total_counts,
                precision=agg_prec, recall=agg_rec, f2=agg_f2, ni=agg_ni,
                reject_rate_overall=agg_rej_overall,
                precision_std=prec_std, recall_std=rec_std, f2_std=f2_std,
                ni_std=ni_std, reject_rate_overall_std=rej_std,
                reject_rate_by_class=(rejN, rejP), eq_cost_matrix=eq_avg
            )
        return out

# --------------------------------------------------------------------------------------
# Main experiment pipeline
# --------------------------------------------------------------------------------------

def run_experiment(X: np.ndarray, y: np.ndarray, n_repeats: int,
                   random_seed: int, solver: str, max_iter: int) -> Tuple[Dict[str, ModelResult], Dict[str, List[float]]]:
    """
    전체 실험 파이프라인을 실행하는 메인 함수.
    수정: 반복별 NI 점수를 수집하는 per_repeat 반환 추가.
    """
    model_names = ["STD_LOGIT", "WEIGHTED_LOGIT", "NI_NO_REJECT", "NI_REJECT"]
    agg = Aggregator(model_names)

    per_repeat = {name: [] for name in model_names}

    for rep in range(n_repeats):
        print(f"Repeat {rep + 1}/{n_repeats}")

        split_seed1 = random_seed + rep
        split_seed2 = random_seed + rep + n_repeats
        model_seed1 = random_seed + rep + (2 * n_repeats)
        model_seed2 = random_seed + rep + (3 * n_repeats)
        search_seed = random_seed + rep + (4 * n_repeats)

        X_tr_val, X_te, y_tr_val, y_te = train_test_split(
            X, y, test_size=0.2, random_state=split_seed1, stratify=y
        )
        X_tr, X_va, y_tr, y_va = train_test_split(
            X_tr_val, y_tr_val, test_size=0.25, random_state=split_seed2, stratify=y_tr_val
        )

        print(f"  Train: {len(y_tr)}, Validation: {len(y_va)}, Test: {len(y_te)}")

        scaler = MinMaxScaler()
        X_tr_s = scaler.fit_transform(X_tr)
        X_va_s = scaler.transform(X_va)
        X_te_s = scaler.transform(X_te)

        base_model = LogisticRegression(solver=solver, max_iter=max_iter, random_state=model_seed1)
        base_model.fit(X_tr_s, y_tr)

        p_va = base_model.predict_proba(X_va_s)[:, 1]
        p_te = base_model.predict_proba(X_te_s)[:, 1]

        # --- NI_NO_REJECT 모델 최적화 및 평가 ---
        res = minimize_scalar(objective_alpha, bounds=(0.001, 1.0), method='bounded', args=(p_va, y_va))
        alpha_mean = float(res.x)
        y_pred_ni_no_rej = pred_nonabstain_with_alpha(p_te, alpha_mean)
        cnt_ni_no = count_binary(y_te, y_pred_ni_no_rej)
        ni_no = ni_from_confusion(cnt_ni_no.to_matrix_no_reject(), m=2)
        lam_FP = alpha_mean
        agg.add("NI_NO_REJECT", cnt_ni_no, np.array([[0.0, lam_FP], [1.0, 0.0]]))
        per_repeat["NI_NO_REJECT"].append(float(ni_no))

        # --- NI_REJECT 모델 최적화 및 평가 ---
        search_rng = np.random.RandomState(search_seed)
        best_overall_ni = -1.0
        best_overall_Tr_pair = (0.0, 0.0)
        n_initial_points = 100

        for _ in range(n_initial_points):
            start_tr_n = search_rng.uniform(0, 0.95)
            start_tr_p = search_rng.uniform(0, 1.0 - start_tr_n)
            start_u, start_v = _Tr_to_uv(start_tr_n, start_tr_p)

            res_powell = minimize(
                objective_uv_Tr,
                np.array([start_u, start_v]),
                args=(p_va, y_va, alpha_mean),
                method='Powell',
                options={'maxiter': 30, 'xtol': 1e-2}
            )

            current_ni = -res_powell.fun
            if current_ni > best_overall_ni:
                best_overall_ni = current_ni
                best_overall_Tr_pair = _uv_to_Tr(float(res_powell.x[0]), float(res_powell.x[1]))

        TrN_opt, TrP_opt = best_overall_Tr_pair
        y_pred_ni_rej = pred_abstain_with_Tr(p_te, TrN_opt, TrP_opt)
        cnt_ni_rej = count_binary(y_te, y_pred_ni_rej)

        denom = max(1e-9, 1.0 - TrN_opt - TrP_opt)
        lam_RN = float(max(0.0, (TrN_opt * (1.0 - TrP_opt) - TrN_opt * TrP_opt * lam_FP) / denom))
        lam_RP = float(max(0.0, (-TrN_opt * TrP_opt + (1.0 - TrN_opt) * TrP_opt * lam_FP) / denom))
        eq_cost_rej = np.array([[0.0, lam_FP, lam_RN], [1.0, 0.0, lam_RP]])
        agg.add("NI_REJECT", cnt_ni_rej, eq_cost_rej)
        ni_rej = ni_from_confusion(cnt_ni_rej.to_matrix_with_reject(), m=2)
        per_repeat["NI_REJECT"].append(float(ni_rej))

        # --- Baselines (테스트 세트로 평가) ---
        # STD_LOGIT
        y_pred_std = (p_te >= 0.5).astype(int)
        cnt_std = count_binary(y_te, y_pred_std)
        agg.add("STD_LOGIT", cnt_std, np.array([[0.0, 1.0], [1.0, 0.0]]))
        ni_std = ni_from_confusion(cnt_std.to_matrix_no_reject(), m=2)
        per_repeat["STD_LOGIT"].append(float(ni_std))

        # WEIGHTED_LOGIT
        wt_model = LogisticRegression(solver=solver, max_iter=max_iter, random_state=model_seed2)
        wt_model.fit(X_tr_s, y_tr)
        p_te_wt = wt_model.predict_proba(X_te_s)[:, 1]


        N = len(y_tr)
        N1 = np.sum(y_tr)
        N0 = N - N1
        y_pred_wt = (p_te_wt >= N1/N).astype(int)
        cost_FN = N/N1
        cost_FP = N/N0
        eq_cost_wt = np.array([[0.0, cost_FP], [cost_FN, 0.0]])

        cnt_wt = count_binary(y_te, y_pred_wt)
        agg.add("WEIGHTED_LOGIT", cnt_wt, eq_cost_wt)
        ni_wt = ni_from_confusion(cnt_wt.to_matrix_no_reject(), m=2)
        per_repeat["WEIGHTED_LOGIT"].append(float(ni_wt))

    return agg.summarize(), per_repeat


def print_results(results: Dict[str, ModelResult]):
    """
    실험 결과를 보기 좋은 형식으로 출력하는 함수
    """
    print("\n" + "="*130)
    print(" " * 55 + "FINAL RESULTS")
    print("="*130)
    print(f"{'Model':<20} {'Precision (μ ± σ)':<22} {'Recall (μ ± σ)':<22} {'F2-Score (μ ± σ)':<22} {'NI-Score (μ ± σ)':<22} {'Reject Rate (μ ± σ)':<22}")
    print("-" * 130)
    for name, result in results.items():
        prec_str = f"{result.precision:.4f} ± {result.precision_std:.4f}"
        rec_str = f"{result.recall:.4f} ± {result.recall_std:.4f}"
        f2_str = f"{result.f2:.4f} ± {result.f2_std:.4f}"
        ni_str = f"{result.ni:.4f} ± {result.ni_std:.4f}"
        rej_str = f"{result.reject_rate_overall:.4f} ± {result.reject_rate_overall_std:.4f}"
        print(f"{name:<20} {prec_str:<22} {rec_str:<22} {f2_str:<22} {ni_str:<22} {rej_str:<22}")
    print("-" * 130)

    print("\n--- Detailed Information (Aggregated over all runs) ---\n")
    for name, result in results.items():
        print(f"=== {name} ===")
        print("Confusion Matrix (sum):")
        if result.reject_rate_overall > 0:
            print(result.counts.to_matrix_with_reject())
        else:
            print(result.counts.to_matrix_no_reject())
        print("\nEquivalent Cost Matrix (avg):")
        print(np.round(result.eq_cost_matrix, 4))
        if result.reject_rate_overall > 0:
            print(f"\nReject Rate by Class: N={result.reject_rate_by_class[0]:.4f}, P={result.reject_rate_by_class[1]:.4f}")
        print("-" * 30)

def main():
    """
    스크립트 실행을 위한 메인 함수.
    """
    class Args:
        data = 'data.csv'
        target = 'Bankrupt?'
        id_col = None
        n_repeats = 20
        seed = 42
        solver = 'liblinear'
        max_iter = 1000

    args = Args()

    try:
        X, y, _ = load_dataset(args.data, target=args.target, id_col=args.id_col)

        print(f"Data '{args.data}' loaded. Samples: {X.shape[0]}, Features: {X.shape[1]}")
        print(f"Settings: Hold-out (60:20:20), repeats={args.n_repeats}, stratified=True")
        print("-" * 50)

        results, per_repeat = run_experiment(
            X, y,
            n_repeats=args.n_repeats,
            random_seed=args.seed,
            solver=args.solver,
            max_iter=args.max_iter,
        )
        print_results(results)

        from scipy.stats import wilcoxon
        a = np.array(per_repeat["NI_REJECT"])
        b = np.array(per_repeat["NI_NO_REJECT"])
        if a.shape == b.shape and a.size > 0:
            stat, p = wilcoxon(a, b, alternative='greater')
            mean_a, std_a = a.mean(), a.std(ddof=1); mean_b, std_b = b.mean(), b.std(ddof=1)
            diff = a - b; mean_diff = diff.mean(); sd_diff = diff.std(ddof=1)
            cohend = mean_diff / sd_diff if sd_diff > 0 else float('nan')
            print("\nWilcoxon signed-rank test (NI_REJECT > NI_NO_REJECT):")
            print(f"  stat = {stat:.3f}, p-value = {p:.3e}"); print(f"  NI_REJECT: mean={mean_a:.4f} ± {std_a:.4f}"); print(f"  NI_NO_REJECT: mean={mean_b:.4f} ± {std_b:.4f}"); print(f"  mean(diff)={mean_diff:.4f}, sd(diff)={sd_diff:.4f}, paired Cohen's d={cohend:.3f}")

    except FileNotFoundError:
        print(f"오류: '{args.data}' 파일을 찾을 수 없습니다. 'data.csv'라는 이름으로 데이터 파일을 현재 폴더에 준비해주세요.")
    except (KeyError, ValueError) as e:
        print(f"데이터 처리 오류: {e}. 데이터 파일의 타겟 변수 이름이나 형식을 확인해주세요.")

if __name__ == "__main__":
    main()



# 추가할 import
from sklearn.datasets import make_classification

def generate_and_save_imbalanced_csv(
    filename: str = "synthetic_bankrupt_9to1.csv",
    n_samples: int = 6819,
    n_features: int = 94,
    n_informative: int = 10,
    n_redundant: int = 5,
    weight_positive: float = 0.1,
    random_state: int = 42
) -> str:
    """
    9:1 불균형 합성 데이터 생성 후 CSV로 저장.
    반환값: 저장된 파일명
    """
    X, y = make_classification(
        n_samples=n_samples,
        n_features=n_features,
        n_informative=n_informative,
        n_redundant=n_redundant,
        n_repeated=0,
        n_classes=2,
        weights=[1.0 - weight_positive, weight_positive],
        class_sep=1.0,
        shuffle=True,
        random_state=random_state,
    )

    col_names = [f"feat_{i:03d}" for i in range(1, n_features + 1)]
    df = pd.DataFrame(X, columns=col_names)
    # 기존 코드에서 기대하는 타깃명 'Bankrupt?'로 저장
    df["Bankrupt?"] = y
    df.to_csv(filename, index=False)
    print(f"Saved synthetic imbalanced dataset to '{filename}' (n={n_samples}, features={n_features}, pos_ratio={weight_positive})")
    return filename

# main() 실행 전에 합성파일 생성 후 기존 흐름 사용
generate_and_save_imbalanced_csv(filename="synthetic_bankrupt_9to1.csv",
                                n_samples=5000, n_features=94, weight_positive=0.1, random_state=42)

# 그리고 Args.data를 "synthetic_bankrupt_9to1.csv"로 바꿔서 기존 코드로 실행